name: moper_complex_api
description: Shelf API for the Moper Complex attendance platform.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

dependencies:
  crypto: ^3.0.7
  mongo_dart: ^0.10.9
  shelf: ^1.4.2
  shelf_router: ^1.1.2

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
